### ISSUE TITLE
Running Classes using ParallelComputer is not generating reports 

### ISSUE THREAD

**Issue by qualityking** [junit-team/junit#1102]
I am using Junit with selenium for my webapplication. 

alright, so code goes like this 

```java

public class FullSuite {
	 @Test
	 public void main(){
		 Class[] cls={ Project1.GlobalStatic.class, Project2.GlobalStatic.class};
		 JUnitCore.runClasses(ParallelComputer.classes(), cls);  
	 }	 
}
```

So here i am planning to run Project1 and Project2 (Junit TestSuites) in parallel and as expected they are working like charm. 
The only issue (which is very critical in nature) that it is not generating reporting tree, which is dragging me towards TestNG... 

A little research. 
In TestNG reports Tree gets generated perfectly alright when using to run in parallel, but the issue is, though it is running in parallel, it is doing the task one by one, looks like using a single thread which is awful.

**Comment by kcooney** [comment]
Your test methods shouldn't call JUnitCore; the code running the tests (your IDE or build system) uses JUnitCore.

How do you usually run your tests?

FYI: the Maven Surefire plugin has support for running tests in parallel

**Comment by qualityking** [comment]
I am currently running them from IDE only.. using them with UI automation testing selenium.. i want to run them in parallel only, but along with reports, can you please suggest, if possible using current JUnit or i need to Fork it.

**Comment by kcooney** [comment]
Check the documentation of your IDE to see if there is a way to run the tests in parallel. Alternatively, create a custom runner that extends `BlockJUnit4ClassRunner` that runs your tests in parallel. We'd be open to suggestions on how to make this easier, so if you have ideas, please create a new feature request. It's a touch problem, because as soon as you run tests in parallel you need an easy way to specify that a method or rule should not be run in parallel,.
