### ISSUE TITLE
Junit should come with predefined Category classes to use as @Category to cover frequent usecases

### ISSUE THREAD

**Issue by sarod** [junit-team/junit#1103]
Lots of people are using Category to indicate similar things:
* How fast is a test to execute (SlowTests, FastTests)
* The type of test (UnitTests, AcceptanceTests, PerformanceTests...)

Junit should probably come with a predefined set of Classes that one can use for such standard usecases.
This would allow for a more homogeneous code bases accross projects.

**Comment by kcooney** [comment]
I think it would be challenging to come up with a set of predefined categories that would be useful to everyone. Users can create their own categories by just creating tests, so if you want to make your projects more consistent, you can create your own library with standard categories that make sense for you.

If there's some benefit to JUnit providing these that I'm missing, let me know, otherwise since it's so trivial to define your own categories, I'm tempted to close the bug.

**Comment by sarod** [comment]
Defining categories is technically very simple. However when starting a project it is not always obvious what kind of categories could be useful. Having predefined categories that reflect the commonly encountered usecases could help.
Another benefit share common conventions for the categories across the Junit community to ease. However I agree that it could be challenging to come up with a set of categories that would be meaningful for everyone.

**Comment by kcooney** [comment]
How about we update the wiki to list classes for common use cases, and we add a link to that page from the categories runner javadoc?

**Comment by sarod** [comment]
That could be a good start.

**Comment by kcooney** [comment]
@sarod Feel free to add a section for this to this page: https://github.com/junit-team/junit/wiki/Categories

Once you're done, send us a pull request adding a link from `Categories.java` to that wiki page.

**Comment by sarod** [comment]
I updated the wiki with a first version
https://github.com/junit-team/junit/wiki/Categories#typical-usages-for-categories

**Comment by kcooney** [comment]
Looks good. Thanks! Please feel free to send us a pull request adding a link to the Categories wiki page from the Categories javadoc
