### ISSUE TITLE
Update to Java 7

### ISSUE THREAD

**Issue by marcphilipp** [junit-team/junit#1146]
We've already decided to move on to Java 6 in JUnit 5. Java 6 has reached end-of-life over two years ago. I think we should skip JDK 6 and move on to JDK 7.

**Comment by marcphilipp** [comment]
@junit-team/junit-committers What are your thoughts on this?

**Comment by baev** [comment]
> Java 6 has reached end-of-life over two years ago

I guess it's not a good enough reason to move on Java 7 (8 or higher). There are lots of projects still uses java 6 for some reasons (such as Intellij IDEA).

**Comment by Tibor17** [comment]
I think it's not the argument because your production code like IntelliJ IDEA can be still built with javac 6 but the tests may already use junit@java8 as long as these are two different classpaths in compiler.

**Comment by baev** [comment]
Sometimes you can't upgrade your build environment to use higher jdk. I don't see any reason to move on 1.7

**Comment by Tibor17** [comment]
Cannot upgrade or somebody does not want to upgrade. Of course I know the situation but it does not mean the the world has to stop because of fee individuals. It's the same in my company where an admin or manager is frustrated but we and external companies and customer are pushing them to use JDK8 - it's the question of time to have it.

**Comment by kcooney** [comment]
JUnit is used in a great number of environments, some of which cannot easily upgrade their JDK.

Are there features in JDK 7 that we want? If not, then I strongly feel that we should release JUnit 5 with a requirement of JDK 6.

**Comment by Tibor17** [comment]
Remember just big bang junit made with java8 features somewhere on google and propose in junit5.
Let's wait for that maybe in junit7.

**Comment by kcooney** [comment]
@Tibor the Lambda features are planned as an extension to JUnit. JUnit 5 will not require Java 8.

Remember that people use JUnit in GWT and Android, neither of which support Java 8.

**Comment by kcooney** [comment]
I propose that we release JUnit 5 soon requiring JDK 6, and see how the community reacts. I don't think we need to wait for.specific features to land before we release JUnit 5 (though it might be good to know what methods we might need to delete or break for JUnit Lambda so we can deprecate them now).

**Comment by tcompart** [comment]
I am a little bit confused. Why do you think that every project and every one, who is using junit, will also upgrade junit but not their jdk?!
My opinion would be that they should not upgrade to the latest version of junit then. Otherwise junit is compiled with a buggy jdk with no security fixes anymore. And this should not be a bugfix release but a minor release upgrade: 4.13, right?

What are your thoughts regarding compile and runtime features? Maybe you can compile with jdk7, but run also on jdk5 environments because you do not use jdk7 features?

**Comment by Tibor17** [comment]
@tcompart 
They want to delete longstanding deprecated staff in that increasing the major version clearly declares broken compatibility as necessary.

**Comment by kcooney** [comment]
@tcompart I don't think anyone said that every project using JUnit would want to upgrade JUnit but not their JDK. Some of us are saying a number of projects have challenges upgrading their JDK.

It's perfectly fine to use a jar compiled with JDK 6 with projects that use JRE 7 or 8, so we aren't holding people back by not upgrading JUnit *unless there are APIs we can't support with JDK 6*. So the question is does JUnit *need* any features that require JDK 7. If the answer is no, then there is some small percentage of users that won't see bug fixes or new features if we change the required JDK to 7. So what's the motivation for the upgrade?

Note that one of the reasons we decided to upgrade to JDK 6 in JUnit 5 is because we had a few people making pull requests that used some APIs that only exist in JDK 6 (`java.util.ServiceLoader` was one example).

I can reach out to the GWT team to see what level of JDK 7 features are supported by GWT.

Android apparently does support JDK 7: http://stackoverflow.com/questions/24040032/jdk-7-and-android-ide

BTW, I think we already agreed that we would only update the required JDK in a major release (in the future, we will try not to make braking changes in a minor or bugfix release).

**Comment by Tibor17** [comment]
see #1148, due to hamcrest-junit 2.0.0.0 instead of 1.3, the junit moves to JDK7 instead of JDK6.
I would also like to see breaking production (src/main/java) dependency on hamcrest as well (only in src/test/java) and #1148 does this.
Because of deprecations politics would you jump directly from 4.12 to 5.0 with all changes like removing production dependency on Hamcrest, removing deprecations, adding javac -source 1.7 -traget 1.7 ?

**Comment by kcooney** [comment]
@Tibor17 If we go by the current depreciation policy, we would have to deprecate the Hamcrest methods, release a new version of JUnit (as 4.13 or 5.0), then wait two years before we can remove the methods.

Let's please not upgrade Hamcrest in JUnit 5. The last Hamcrest upgrade was painful for us and our users.

If we are going to remove the Hamcrest dependencies from JUnit, I would personally rather migrate our tests from Hamcrest to Truth.

**Comment by marcphilipp** [comment]
Sorry about the confusion this issue has caused. I should have explained my motivation a bit... 

You've figured it out in the meantime: Upgrading to JDK 7 would allow us to use hamcrest-junit 2.0.0.0 and thus an easy part to solve #1145 via #1148. I've opened this issue to collect your opinions on this. Having heard them now, I'm also a bit skeptical we need JDK 7.

There are other ways to solve #1145 of course. Please let's discuss them in that issue.

**Comment by marcphilipp** [comment]
Closing this issue, maybe in JUnit 6.
